### ISSUE TITLE
Migrate to MIT license

### ISSUE THREAD

**Issue by HeinrichReimer** [HeinrichReimer/material-drawer#87]
As the MIT is easier to include for developers using this library I want to change the library license from Apache license 2.0 to the more permissive and simpler MIT license.
Because the license change would give library users more permissions than with the APLv2 all contributors need to approve this change.

Here's a list of all contributors to keep track of all confirmations:
- [x] @HeinrichReimer 
- [x] @IgorGanapolsky  
- [x] @jkwiecien  
- [ ] @guilty787  
- [ ] @i906   

I'll notify the contributors so that we can change the license ASAP.

**Comment by HeinrichReimer** [comment]
Fixed by b635393fc7836611cc661ef04862d24996e796ed

**Comment by DragiPandeliev** [comment]
I guess you missed  to update this:
https://github.com/heinrichreimer/material-drawer#license
